// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzevdyqopppbyqegvvcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6ZXZkeXFvcHBwYnlxZWd2dmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NzAyOTEsImV4cCI6MjA3MTI0NjI5MX0.b8PIVoSeXW_NLy-pb2iVHUv1CLKroN8h3JbAdTcyEHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});